# Generated by Django 4.2.5 on 2023-11-05 17:40

from django.db import migrations, models
import product_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to=product_api.models.upload_location),
        ),
    ]
