export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART"
export const MODIFY_QUNATITY_OF_A_ITEM = "MODIFY_QUNATITY_OF_A_ITEM"
export const CLEAR_CART = "CLEAR_CART"